name: Release

on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (x.y.z)'
        required: true
        default: '0.0.0'

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.2'
          cache: true
          modules: ''

      - name: Extract version
        id: ver
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          fi

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Filter *.slnx | Select-Object -First 1
          msbuild $sln.FullName `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:AppVersion=${{ steps.ver.outputs.version }} `
            /p:QtInstall=$env:QT_ROOT_DIR `
            /m
          Add-Content -Path $env:GITHUB_ENV -Value "PLUGIN_NAME=$($sln.BaseName)"

      - name: Deploy
        shell: pwsh
        run: |
          Write-Host "Plugin name: $env:PLUGIN_NAME"
          mkdir dist
          Copy-Item x64/Release/$env:PLUGIN_NAME.dll dist/

      - name: Zip
        shell: pwsh
        run: |
          Compress-Archive dist/* $env:PLUGIN_NAME-${{ steps.ver.outputs.version }}.zip

      - uses: actions/upload-artifact@v6
        with:
          name: zip
          path: ${{ steps.build.outputs.plugin_name }}-*.zip
          if-no-files-found: error


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: artifacts
          pattern: zip
          merge-multiple: true

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ inputs.version || github.ref_name }}
          files: artifacts/*
          generate_release_notes: true